### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by RainbowAlpaca521** [Brandonjhd/unipus-ai#1]
打开后登录过期怎么办，手机电脑账户都退出了，cookie也删干净了

**Comment by Brandonjhd** [comment]
我目前没遇到过这种情况neq🤔
________________________________
寄件者: RainbowAlpaca521 ***@***.***>
寄件日期: Sunday, December 8, 2024 2:29:23 PM
收件者: Brandonjhd/unipus-ai ***@***.***>
副本: Subscribed ***@***.***>
主旨: [Brandonjhd/unipus-ai] 求助 (Issue #1)


打开后登录过期怎么办，手机电脑账户都退出了，cookie也删干净了

**Comment by Brandonjhd** [comment]
v2.0.0已发布，可以试试
